artifacts_roots: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_URL: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
  local_data_file: artifact/data_ingestion/data.zip
  unzip_dir: artifact/data_ingestion

prepare_base_model:
  root_dir: artifact/prepare_base_model
  base_model_path: artifact/prepare_base_model/base_model.h5
  updated_base_model_path: artifact/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifact/prepare_callbacks
  tensorboard_root_log_dir: artifact/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifact/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifact/training
  trained_model_path: artifact/training/model.h5

evaluation:
  root_dir: artifact/evaluation
  score_file_path: artifact/evaluation/scores.json

params:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3]
  BATCH_SIZE: 16
  INCLUDE_TOP: False
  EPOCHS: 1
  CLASSES: 2
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01
  